global: 
  sendAnonymousUsage: false
  checkNewVersion: false

entrypoints:
  web:
    address: ":80"
    http: 
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: ":443"
    http:
      tls:
        certResolver: letsentcrypt

  metrics:
    address: ":8082"

certificatesResolver:
  letsencrypt:
    acme:
      email: bernardo.corais@gmail.com
      storage: /letsencrypt/acme.json
      tlsChallenge: {}
      
log:
  level: INFO
  format: json

accesslog:
  format: json
  fields: 
    defaultMode: keep
    names: 
      RequestPath: keep
      RequestMethod: keep
      RequestHost: keep
      RequestAddr: keep
      RequestProtocol: keep
    headers:
      defaultMode: keep
      names:
        User-Agent: keep
        X-Forwarded-For: keep
        Referer: keep

metrics: 
  prometheus: 
    addEntryPointsLabels: true
    addRoutersLabels: true
    addServicesLabels: true
    entryPoint: metrics
    manualRouting: false

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

experimental:
  plugins:
    fail2ban:
      moduleName: "github.com/tomMoulard/fail2ban"
      version: "v0.8.9"

api:
  dashboard: true
